### ISSUE TITLE
Parser support for multiple focusconcepts

### ISSUE THREAD

**Issue by mertenssander** [mertenssander/postco#15]
Hi @basharmsen ,
I can't seem to get the parser to accept multiple focus concepts.
My attempts to change the template in template #2 have resulted in no change in output of the parser - syntax check by https://apg.ihtsdotools.org/SCT-etl.html gives the template a pass.

`[[+tok (=== <<<) @DefStatus]]  281647001 |Adverse reaction (disorder)| + 64572001 |Disease| :
        {  
          246075003 |Causative agent (attribute)|   =  [[+id (< 105590001 |Substance (substance)| ) @Substance]],
          370135005 |Pathological process (attribute)|   =  472964009 |Allergic process (qualifier value)| 
        }`

Do you have any idea?

**Comment by basharmsen** [comment]
Hi @mertenssander,

I think it should be fixed now.

**Comment by mertenssander** [comment]
@hielkema Could you provide a template with multiple focus concepts to test this functionality?

**Comment by hielkema** [comment]
I've pushed one into the development branch: koortsDoorInfectieMet.xml

**Comment by mertenssander** [comment]
Seems to work perfectly! Closed.
