### ISSUE TITLE
Narrow constraint further to parts of mamma?

### ISSUE THREAD

**Issue by mertenssander** [mertenssander/postco#20]
https://github.com/mertenssander/postco/blob/b0f8cd8611e1b746bf020bbabc0aec5bb62d9323/SnomedTemplateService/SnomedTemplateService.Web/SnomedTemplates/nictiz/MammaCarcinoom_1605716520.xml#L23

Hi @hielkema ,
I was testing entering information in template MammaCarcinoom, and got fairly broad results for the 'locatie: welk kwadrant?' field. Would it be feasible to change this constraint to <119184005 | gedeelte van mamma (lichaamsstructuur) |, or is this too narrow?

**Comment by hielkema** [comment]
If you want to restrict it to quadrant of mamma, you should use 272670002 |structuur van kwadrant van mamma (lichaamsstructuur)|. 19184005 | gedeelte van mamma (lichaamsstructuur) | is actually almost as generic as the current setting.

I'd discuss with Floor first how she intends to use the template. If she also needs to create postcoordinations for tumor of the lactating mamma, or the entire mamma, then this template would no longer be usable with the new restriction.

**Comment by hielkema** [comment]
Discussed with Floor. This template is no longer necessary, they have decided not to register the quadrant. This template will probably not be used, but we'll leave it in as an example.
