### ISSUE TITLE
DefinitionStatus slot not supported

### ISSUE THREAD

**Issue by hielkema** [mertenssander/postco#21]
The template koortsDoorInfectieMet_1605716520.xml contains a slot for definitionstatus, where the author can choose whether the postcoordination expresses the intended meaning partially (<<<) or sufficiently (===). In the interface however no field is shown to choose between === and <<<, and the resulting expression always has prefix ===.

@mertenssander and @basharmsen I don't know whether this is due to the parser or the interface or both. If complicated we could decide not to support this feature at all; but at least we should document that decision.

**Comment by basharmsen** [comment]
The parser supports definition status slots but [the results format](https://github.com/mertenssander/postco/blob/development/model/template_model_0.0.2.js) for the web service doesn't. To support this feature this format should be extended. Adapting the webservice for this should be easy. I think that implementing it in the frontend will be the most work. @mertenssander Will this be a lot of work for you?

**Comment by mertenssander** [comment]
@basharmsen This should not be too difficult. If you could add it to the model for the frontend in an appropriate place I will implement it in due time.

**Comment by basharmsen** [comment]
Definition status is now supported by template service.

**Comment by mertenssander** [comment]
#
